events {}

http {
  upstream products_service {
    server products-service:3000;
  }

  server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header X-Internal-Token $http_x_internal_token;
    proxy_set_header X-Request-Id $request_id;

    location = /api/v1/products {
      proxy_pass http://products_service;
    }

    location ^~ /api/v1/products/ {
      proxy_pass http://products_service;
    }

    location = /docs {
      proxy_pass http://products_service;
    }

    location ^~ /docs/ {
      proxy_pass http://products_service;
    }

    location = /docs-json {
      proxy_pass http://products_service;
    }

    location ^~ /internal/ {
      return 404;
    }

    location / {
      return 404;
    }
  }
}
