export const STOCK_WRITE_REPOSITORY = Symbol('STOCK_WRITE_REPOSITORY');
export const STOCK_READ_REPOSITORY = Symbol('STOCK_READ_REPOSITORY');
export const STOCK_EVENT_PUBLISHER = Symbol('STOCK_EVENT_PUBLISHER');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
